services:
  zipkin-server:
    image: openzipkin/zipkin:latest
    ports:
      - 9411:9411
    restart: always
    depends_on:
      - rabbit-mq
    environment:
      RABBIT_URI: amqp://guest:guest@rabbit-mq:5672
    networks:
      - erudio-network

  rabbit-mq:
    image: rabbitmq:3.8.14-management
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - erudio-network

  book-db:
    image: mysql:8.0.33
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_USER: docker
      MYSQL_PASSWORD: admin123
      MYSQL_DATABASE: book_service
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3310
    ports:
      - 3310:3310
    expose:
      - 3310
    networks:
      - erudio-network

  cambio-db:
    image: mysql:8.0.33
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_USER: docker
      MYSQL_PASSWORD: admin123
      MYSQL_DATABASE: cambio_service
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3308
    ports:
      - 3308:3308
    expose:
      - 3308
    networks:
      - erudio-network

  naming-server:
    image: olucasnascimento/naming-server:0.0.1-SNAPSHOT
    ports:
      - 8761:8761
    networks:
      - erudio-network

  api-gateway:
    image: olucasnascimento/api-gateway:0.0.1-SNAPSHOT
    ports:
      - 8765:8765
    depends_on:
      - naming-server
      - rabbit-mq
    environment:
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
      MANAGEMENT.ZIPKIN.TRACING.ENDPOINT: http://zipkin-server:9411/api/v2/spans
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      RABBIT_URI: amqp://guest:guest@rabbit-mq:5672
      SPRING_RABBITMQ_HOST: rabbit-mq
      SPRING_ZIPKIN_SENDER_TYPE: rabbit
    networks:
      - erudio-network

  cambio-service:
    image: olucasnascimento/cambio-service
    restart: always
    build:
      context: .
      dockerfile: cambio-service/DockerFile
    environment:
      TZ: America/Sao_Paulo
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
      MANAGEMENT.ZIPKIN.TRACING.ENDPOINT: http://zipkin-server:9411/api/v2/spans
      RABBIT_URI: amqp://guest:guest@rabbit-mq:5672
      SPRING_RABBITMQ_HOST: rabbit-mq
      SPRING_ZIPKIN_SENDER_TYPE: rabbit
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      SPRING.APPLICATION.NAME: cambio-service
      SPRING.DATASOURCE.URL: jdbc:mysql://cambio-db:3308/cambio_service?useSSL=false&use&serverTimezone=UTC&enabledTLSProtocols=TLSv1.2
      SPRING.DATASOURCE.USERNAME: root
      SPRING.DATASOURCE.PASSWORD: admin123
      SPRING.FLYWAY.URL: jdbc:mysql://cambio-db:3308/cambio_service?useSSL=false&use&serverTimezone=UTC&enabledTLSProtocols=TLSv1.2
      SPRING.FLYWAYSCHEMAS: cambio_service
      SPRING.FLYWAYUSER: root
      SPRING.FLYWAYPASSWORD: admin123
    ports:
      - 8000:8000
    depends_on:
      - naming-server
      - cambio-db
      - rabbit-mq
    networks:
      - erudio-network

  book-service:
    image: olucasnascimento/book-service
    restart: always
    build:
      context: .
      dockerfile: book-service/DockerFile
    environment:
      TZ: America/Sao_Paulo
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
      MANAGEMENT.ZIPKIN.TRACING.ENDPOINT: http://zipkin-server:9411/api/v2/spans
      RABBIT_URI: amqp://guest:guest@rabbit-mq:5672
      SPRING_RABBITMQ_HOST: rabbit-mq
      SPRING_ZIPKIN_SENDER_TYPE: rabbit
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      SPRING.APPLICATION.NAME: book-service
      SPRING.DATASOURCE.URL: jdbc:mysql://book-db:3310/book_service?useSSL=false&use&serverTimezone=UTC&enabledTLSProtocols=TLSv1.2
      SPRING.DATASOURCE.USERNAME: root
      SPRING.DATASOURCE.PASSWORD: admin123
      SPRING.FLYWAY.URL: jdbc:mysql://book-db:3310/book_service?useSSL=false&use&serverTimezone=UTC&enabledTLSProtocols=TLSv1.2
      SPRING.FLYWAYSCHEMAS: book_service
      SPRING.FLYWAYUSER: root
      SPRING.FLYWAYPASSWORD: admin123
    ports:
      - 8100:8100
    depends_on:
      - naming-server
      - book-db
      - rabbit-mq
    networks:
      - erudio-network

networks:
  erudio-network:
    driver: bridge